# Generated by Django 4.0.4 on 2022-05-24 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogdefranco', '0002_alter_comentarios_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
