# Generated by Django 4.0.4 on 2022-05-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='last_name',
        ),
    ]
