# Generated by Django 4.0.4 on 2022-05-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilusuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(default='No hay nada por aquí...', max_length=700),
        ),
    ]
