# Generated by Django 4.0.4 on 2022-05-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfilusuario_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(default='No hay nada por aquí...', max_length=300),
        ),
    ]
